In [ ]:
import numpy as np
import pandas as pd

df=pd.read_csv("/content/Iris.csv")
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
df.isna().sum()  #To know missing value

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
df1=df.drop(columns=["Id"],axis=1)  # axis=1 to remove the data in column wise.....#axis=0 to remove data in row wise
print(df1)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df1.dtypes  # To know data types

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
x=df1.drop("Species",axis=1).values  #To get input    #values enn kodthaaal...array ayt covert cheyyam
y=df1["Species"].values  #To get output
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [ ]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
#Testing and training
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
x_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
81             5.5           2.4            3.7           1.0
133            6.3           2.8            5.1           1.5
137            6.4           3.1            5.5           1.8
75             6.6           3.0            4.4           1.4
109            7.2           3.6            6.1           2.5
..             ...           ...            ...           ...
71             6.1           2.8            4.0           1.3
106            4.9           2.5            4.5           1.7
14             5.8           4.0            1.2           0.2
92             5.8           2.6            4.0           1.2
102            7.1           3.0            5.9           2.1

[105 rows x 4 columns]

In [ ]:
x_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
73             6.1           2.8            4.7           1.2
18             5.7           3.8            1.7           0.3
118            7.7           2.6            6.9           2.3
78             6.0           2.9            4.5           1.5
76             6.8           2.8            4.8           1.4
31             5.4           3.4            1.5           0.4
64             5.6           2.9            3.6           1.3
141            6.9           3.1            5.1           2.3
68             6.2           2.2            4.5           1.5
82             5.8           2.7            3.9           1.2
110            6.5           3.2            5.1           2.0
12             4.8           3.0            1.4           0.1
36             5.5           3.5            1.3           0.2
9              4.9           3.1            1.5           0.1
19             5.1           3.8            1.5           0.3
56             6.3           3.3            4.7           1.6
104            6.5           3.0            5.8           2.2
69             5.6           2.5            3.9           1.1
55             5.7           2.8            4.5           1.3
132            6.4           2.8            5.6           2.2
29             4.7           3.2            1.6           0.2
127            6.1           3.0            4.9           1.8
26             5.0           3.4            1.6           0.4
128            6.4           2.8            5.6           2.1
131            7.9           3.8            6.4           2.0
145            6.7           3.0            5.2           2.3
108            6.7           2.5            5.8           1.8
143            6.8           3.2            5.9           2.3
45             4.8           3.0            1.4           0.3
30             4.8           3.1            1.6           0.2
22             4.6           3.6            1.0           0.2
15             5.7           4.4            1.5           0.4
65             6.7           3.1            4.4           1.4
11             4.8           3.4            1.6           0.2
42             4.4           3.2            1.3           0.2
146            6.3           2.5            5.0           1.9
51             6.4           3.2            4.5           1.5
27             5.2           3.5            1.5           0.2
4              5.0           3.6            1.4           0.2
32             5.2           4.1            1.5           0.1
142            5.8           2.7            5.1           1.9
85             6.0           3.4            4.5           1.6
86             6.7           3.1            4.7           1.5
16             5.4           3.9            1.3           0.4
10             5.4           3.7            1.5           0.2

In [ ]:
y_train

81     Iris-versicolor
133     Iris-virginica
137     Iris-virginica
75     Iris-versicolor
109     Iris-virginica
            ...
71     Iris-versicolor
106     Iris-virginica
14         Iris-setosa
92     Iris-versicolor
102     Iris-virginica
Name: Species, Length: 105, dtype: object

In [ ]:
y_test

73     Iris-versicolor
18         Iris-setosa
118     Iris-virginica
78     Iris-versicolor
76     Iris-versicolor
31         Iris-setosa
64     Iris-versicolor
141     Iris-virginica
68     Iris-versicolor
82     Iris-versicolor
110     Iris-virginica
12         Iris-setosa
36         Iris-setosa
9          Iris-setosa
19         Iris-setosa
56     Iris-versicolor
104     Iris-virginica
69     Iris-versicolor
55     Iris-versicolor
132     Iris-virginica
29         Iris-setosa
127     Iris-virginica
26         Iris-setosa
128     Iris-virginica
131     Iris-virginica
145     Iris-virginica
108     Iris-virginica
143     Iris-virginica
45         Iris-setosa
30         Iris-setosa
22         Iris-setosa
15         Iris-setosa
65     Iris-versicolor
11         Iris-setosa
42         Iris-setosa
146     Iris-virginica
51     Iris-versicolor
27         Iris-setosa
4          Iris-setosa
32         Iris-setosa
142     Iris-virginica
85     Iris-versicolor
86     Iris-versicolor
16         Iris-setosa
10         Iris-setosa
Name: Species, dtype: object

In [ ]:
#Next process is normalisation
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
x_test

array([[ 0.3100623 , -0.49582097,  0.48403749, -0.05143998],
       [-0.17225683,  1.92563026, -1.26851205, -1.26670948],
       [ 2.23933883, -0.98011121,  1.76924049,  1.43388941],
       [ 0.18948252, -0.25367584,  0.36720086,  0.35364985],
       [ 1.15412078, -0.49582097,  0.54245581,  0.21861991],
       [-0.53399618,  0.95704977, -1.38534869, -1.13167953],
       [-0.29283662, -0.25367584, -0.15856401,  0.08358997],
       [ 1.27470056,  0.2306144 ,  0.71771076,  1.43388941],
       [ 0.43064208, -1.9486917 ,  0.36720086,  0.35364985],
       [-0.05167705, -0.73796609,  0.01669095, -0.05143998],
       [ 0.79238143,  0.47275953,  0.71771076,  1.02879957],
       [-1.25747488, -0.01153072, -1.443767  , -1.53676936],
       [-0.4134164 ,  1.19919489, -1.50218532, -1.40173942],
       [-1.1368951 ,  0.2306144 , -1.38534869, -1.53676936],
       [-0.89573553,  1.92563026, -1.38534869, -1.26670948],
       [ 0.55122187,  0.71490465,  0.48403749,  0.4886798 ],
       [ 0.79238143, -0.01153072,  1.12663899,  1.29885946],
       [-0.29283662, -1.22225633,  0.01669095, -0.18646992],
       [-0.17225683, -0.49582097,  0.36720086,  0.08358997],
       [ 0.67180165, -0.49582097,  1.00980236,  1.29885946],
       [-1.37805466,  0.47275953, -1.32693037, -1.40173942],
       [ 0.3100623 , -0.01153072,  0.60087413,  0.75873969],
       [-1.01631531,  0.95704977, -1.32693037, -1.13167953],
       [ 0.67180165, -0.49582097,  1.00980236,  1.16382952],
       [ 2.4804984 ,  1.92563026,  1.4771489 ,  1.02879957],
       [ 1.033541  , -0.01153072,  0.77612908,  1.43388941],
       [ 1.033541  , -1.22225633,  1.12663899,  0.75873969],
       [ 1.15412078,  0.47275953,  1.18505731,  1.43388941],
       [-1.25747488, -0.01153072, -1.443767  , -1.26670948],
       [-1.25747488,  0.2306144 , -1.32693037, -1.40173942],
       [-1.49863445,  1.44134002, -1.67744028, -1.40173942],
       [-0.17225683,  3.378501  , -1.38534869, -1.13167953],
       [ 1.033541  ,  0.2306144 ,  0.30878254,  0.21861991],
       [-1.25747488,  0.95704977, -1.32693037, -1.40173942],
       [-1.73979401,  0.47275953, -1.50218532, -1.40173942],
       [ 0.55122187, -1.22225633,  0.65929245,  0.89376963],
       [ 0.67180165,  0.47275953,  0.36720086,  0.35364985],
       [-0.77515575,  1.19919489, -1.38534869, -1.40173942],
       [-1.01631531,  1.44134002, -1.443767  , -1.40173942],
       [-0.77515575,  2.65206563, -1.38534869, -1.53676936],
       [-0.05167705, -0.73796609,  0.71771076,  0.89376963],
       [ 0.18948252,  0.95704977,  0.36720086,  0.4886798 ],
       [ 1.033541  ,  0.2306144 ,  0.48403749,  0.35364985],
       [-0.53399618,  2.16777538, -1.50218532, -1.13167953],
       [-0.53399618,  1.68348514, -1.38534869, -1.40173942]])

In [ ]:
x_train

array([[-0.4134164 , -1.46440146, -0.10014569, -0.32149987],
       [ 0.55122187, -0.49582097,  0.71771076,  0.35364985],
       [ 0.67180165,  0.2306144 ,  0.95138404,  0.75873969],
       [ 0.91296121, -0.01153072,  0.30878254,  0.21861991],
       [ 1.63643991,  1.44134002,  1.30189395,  1.7039493 ],
       [-0.17225683, -0.25367584,  0.1919459 ,  0.08358997],
       [ 2.11875905, -0.01153072,  1.59398554,  1.16382952],
       [-0.29283662, -0.01153072,  0.36720086,  0.35364985],
       [-0.89573553,  1.19919489, -1.443767  , -1.40173942],
       [ 2.23933883, -0.49582097,  1.65240385,  1.02879957],
       [-0.05167705, -0.73796609,  0.13352758, -0.32149987],
       [-0.77515575,  0.95704977, -1.443767  , -1.40173942],
       [-1.01631531,  1.19919489, -1.50218532, -1.26670948],
       [-0.89573553,  1.92563026, -1.15167541, -1.13167953],
       [-1.01631531, -2.43298195, -0.21698232, -0.32149987],
       [ 0.55122187, -0.73796609,  0.60087413,  0.75873969],
       [-1.25747488,  0.95704977, -1.15167541, -1.40173942],
       [-1.01631531, -0.01153072, -1.32693037, -1.40173942],
       [-0.89573553,  0.71490465, -1.26851205, -0.99664959],
       [-0.29283662, -0.73796609,  0.1919459 ,  0.08358997],
       [-0.89573553,  0.95704977, -1.38534869, -1.40173942],
       [-0.17225683, -0.01153072,  0.1919459 , -0.05143998],
       [ 2.23933883,  1.92563026,  1.65240385,  1.29885946],
       [-1.49863445,  0.47275953, -1.443767  , -1.40173942],
       [ 0.43064208, -0.25367584,  0.25036422,  0.08358997],
       [-0.17225683, -1.22225633,  0.65929245,  1.02879957],
       [-0.4134164 ,  2.89421075, -1.443767  , -1.40173942],
       [ 0.18948252, -0.01153072,  0.54245581,  0.75873969],
       [-0.05167705, -0.73796609,  0.71771076,  0.89376963],
       [ 0.18948252, -1.9486917 ,  0.07510927, -0.32149987],
       [-0.53399618, -0.01153072,  0.36720086,  0.35364985],
       [ 0.43064208,  0.95704977,  0.89296572,  1.43388941],
       [-0.4134164 , -1.70654658,  0.07510927,  0.08358997],
       [-0.53399618,  2.16777538, -1.26851205, -1.13167953],
       [-1.01631531, -1.70654658, -0.33381896, -0.32149987],
       [ 0.67180165, -0.73796609,  0.8345474 ,  0.89376963],
       [-1.01631531,  0.71490465, -1.443767  , -1.40173942],
       [-1.01631531,  0.47275953, -1.56060364, -1.40173942],
       [-0.4134164 , -1.46440146, -0.04172737, -0.18646992],
       [ 1.033541  , -0.01153072,  0.65929245,  0.62370974],
       [-1.1368951 ,  0.2306144 , -1.38534869, -1.53676936],
       [-0.05167705, -0.49582097,  0.71771076,  1.56891935],
       [-1.01631531,  0.95704977, -1.38534869, -1.40173942],
       [-1.01631531,  1.19919489, -1.32693037, -0.86161964],
       [ 0.06890273,  0.47275953,  0.54245581,  0.75873969],
       [-0.89573553, -1.22225633, -0.50907391, -0.18646992],
       [ 1.27470056,  0.47275953,  1.06822067,  1.43388941],
       [ 0.18948252, -0.73796609,  0.71771076,  0.4886798 ],
       [ 0.3100623 , -0.98011121,  1.00980236,  0.21861991],
       [ 2.23933883, -0.01153072,  1.30189395,  1.43388941],
       [-0.4134164 , -1.22225633,  0.07510927,  0.08358997],
       [-1.73979401, -0.25367584, -1.443767  , -1.40173942],
       [-1.8603738 , -0.01153072, -1.61902196, -1.53676936],
       [ 0.18948252, -1.9486917 ,  0.65929245,  0.35364985],
       [ 1.63643991,  0.47275953,  1.24347563,  0.75873969],
       [-1.49863445,  0.2306144 , -1.38534869, -1.40173942],
       [-0.89573553,  1.19919489, -1.443767  , -1.26670948],
       [-1.73979401, -0.01153072, -1.50218532, -1.40173942],
       [ 0.55122187, -1.22225633,  0.60087413,  0.35364985],
       [ 0.55122187,  0.95704977,  1.00980236,  1.56891935],
       [-1.49863445,  0.95704977, -1.443767  , -1.26670948],
       [ 1.15412078, -0.01153072,  0.95138404,  1.16382952],
       [ 0.55122187,  0.71490465,  1.24347563,  1.7039493 ],
       [-1.37805466,  0.47275953, -1.50218532, -1.40173942],
       [ 0.3100623 , -0.25367584,  0.48403749,  0.21861991],
       [ 0.79238143, -0.49582097,  0.42561917,  0.35364985],
       [ 0.43064208, -0.49582097,  0.54245581,  0.75873969],
       [ 1.39528035,  0.47275953,  0.48403749,  0.21861991],
       [ 0.67180165,  0.47275953,  0.8345474 ,  1.43388941],
       [-0.89573553,  1.92563026, -1.32693037, -1.40173942],
       [ 1.27470056,  0.2306144 ,  0.89296572,  1.16382952],
       [ 0.06890273, -0.01153072,  0.1919459 ,  0.35364985],
       [ 0.79238143, -0.01153072,  0.77612908,  1.02879957],
       [-0.17225683, -0.98011121, -0.21698232, -0.32149987],
       [-0.77515575, -0.73796609,  0.01669095,  0.21861991],
       [ 0.3100623 , -0.01153072,  0.42561917,  0.21861991],
       [-1.61921423, -1.70654658, -1.50218532, -1.26670948],
       [ 0.91296121, -0.25367584,  0.42561917,  0.08358997],
       [-0.4134164 , -0.98011121,  0.30878254, -0.05143998],
       [-0.65457597,  1.68348514, -1.38534869, -1.40173942],
       [-0.29283662, -0.01153072,  0.13352758,  0.08358997],
       [ 1.7570197 , -0.25367584,  1.41873058,  0.75873969],
       [ 1.033541  ,  0.71490465,  1.06822067,  1.16382952],
       [-0.89573553,  1.68348514, -1.38534869, -1.13167953],
       [-1.1368951 , -1.46440146, -0.33381896, -0.32149987],
       [ 1.033541  ,  0.71490465,  1.06822067,  1.7039493 ],
       [ 1.63643991, -0.01153072,  1.12663899,  0.4886798 ],
       [-1.1368951 ,  0.2306144 , -1.38534869, -1.53676936],
       [ 1.033541  ,  0.2306144 ,  1.00980236,  1.56891935],
       [-1.1368951 , -0.01153072, -1.443767  , -1.40173942],
       [ 1.27470056,  0.2306144 ,  0.60087413,  0.35364985],
       [ 1.87759948, -0.49582097,  1.30189395,  0.89376963],
       [ 0.55122187, -0.25367584,  1.00980236,  0.75873969],
       [-0.17225683, -0.49582097,  0.13352758,  0.08358997],
       [ 0.79238143, -0.01153072,  0.95138404,  0.75873969],
       [ 0.55122187, -1.70654658,  0.30878254,  0.08358997],
       [ 0.67180165, -0.25367584,  0.25036422,  0.08358997],
       [-0.29283662, -0.49582097,  0.60087413,  1.02879957],
       [ 0.06890273, -0.01153072,  0.71771076,  0.75873969],
       [-0.53399618,  0.95704977, -1.26851205, -1.40173942],
       [ 0.3100623 , -0.49582097,  0.07510927,  0.08358997],
       [-1.1368951 , -1.22225633,  0.36720086,  0.62370974],
       [-0.05167705,  2.40992051, -1.56060364, -1.40173942],
       [-0.05167705, -0.98011121,  0.07510927, -0.05143998],
       [ 1.51586013, -0.01153072,  1.18505731,  1.16382952]])

In [ ]:
#Next process is model creation

from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=7)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [ ]:
#Here we know y_pred=y_test so just print y_test

In [ ]:
y_test

73     Iris-versicolor
18         Iris-setosa
118     Iris-virginica
78     Iris-versicolor
76     Iris-versicolor
31         Iris-setosa
64     Iris-versicolor
141     Iris-virginica
68     Iris-versicolor
82     Iris-versicolor
110     Iris-virginica
12         Iris-setosa
36         Iris-setosa
9          Iris-setosa
19         Iris-setosa
56     Iris-versicolor
104     Iris-virginica
69     Iris-versicolor
55     Iris-versicolor
132     Iris-virginica
29         Iris-setosa
127     Iris-virginica
26         Iris-setosa
128     Iris-virginica
131     Iris-virginica
145     Iris-virginica
108     Iris-virginica
143     Iris-virginica
45         Iris-setosa
30         Iris-setosa
22         Iris-setosa
15         Iris-setosa
65     Iris-versicolor
11         Iris-setosa
42         Iris-setosa
146     Iris-virginica
51     Iris-versicolor
27         Iris-setosa
4          Iris-setosa
32         Iris-setosa
142     Iris-virginica
85     Iris-versicolor
86     Iris-versicolor
16         Iris-setosa
10         Iris-setosa
Name: Species, dtype: object

In [ ]:
print(model.predict(scaler.transform([[6,3,5,7]])))

['Iris-virginica']

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

In [ ]:
#Practical method of accuracy_score
score=accuracy_score(y_test,y_pred)
score

1.0

In [2]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
import pickle
from sklearn.datasets import load_iris


# 1. Load iris dataset
X, y = load_iris(return_X_y=True)

# 2. Create pipeline (scaling + classifier)
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('clf', KNeighborsClassifier(n_neighbors=7))
])

# 3. Train the pipeline
pipeline.fit(X, y)

# 4. Save the trained pipeline to a file
with open("iris.pkl", "wb") as f:
    pickle.dump(pipeline, f)

print(" Iris classifier trained and saved as iris.pkl")

 Iris classifier trained and saved as iris.pkl